# -*- coding: utf-8 -*-
"""
Created on Tue Dec 30 16:52:41 2025

@author: Runhao Lu

This script simulates EEG-like datasets under multiple generative modes and visualizes:
1) Grand-average ERP (mean ± SEM across simulated subjects),
2) PSD (Welch; mean ± SEM),
3) ISPC/PLV summary (bar + SEM),
4) Phase-difference distribution (rose/polar histogram; pooled across subjects).

Notes on design:
- Data are generated by `simulate_data` (imported from simulate_eeg.py).
- ISPC/PLV is computed between frontal vs posterior channel groups derived from CH_NAMES.

"""

import os
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import sem
from scipy.signal import butter, sosfiltfilt, hilbert, welch
from simulate_eeg import simulate_data
import seaborn as sns
from mpl_toolkits.axes_grid1.inset_locator import inset_axes

# ========================= Core Configuration =========================
N_SUBS_TO_RUN = 30
SFREQ = 100
TMIN, TMAX = 0.0, 0.8  # epoch window (s); note: this affects time vector resolution

N_CLASSES = 2
N_TRIALS_PER_CLASS = 40
N_TOTAL_TRIALS = N_TRIALS_PER_CLASS * N_CLASSES

noise_scale = 1.0
RESULT_DIR = r"..."
os.makedirs(RESULT_DIR, exist_ok=True)
OUTPLOT=False

# ========================= Standard 32-Channel System =========================
CH_NAMES = [
    'Fp1', 'Fp2', 'F7', 'F3', 'Fz', 'F4', 'F8', 'FC5', 'FC1', 'FC2', 'FC6',
    'T7', 'C3', 'Cz', 'C4', 'T8', 'TP9', 'CP5', 'CP1', 'CP2', 'CP6', 'TP10',
    'P7', 'P3', 'Pz', 'P4', 'P8', 'PO9', 'O1', 'Oz', 'O2', 'PO10'
]
N_CHANNELS = len(CH_NAMES)

# Region indices derived from channel name prefixes
# Posterior: parietal/occipital/centro-parietal
posterior_idxs = [i for i, name in enumerate(CH_NAMES) if name.startswith(('P', 'O', 'CP'))]

# Frontal: frontal pole + frontal + fronto-central (optional; here strictly name.startswith('F'))
# If you want FC* included as "frontal", change the prefix tuple to ('F', 'FC').
frontal_idxs = [i for i, name in enumerate(CH_NAMES) if name.startswith('F')]

print(f"Posterior Channels ({len(posterior_idxs)}): {[CH_NAMES[i] for i in posterior_idxs]}")
print(f"Frontal Channels ({len(frontal_idxs)}): {[CH_NAMES[i] for i in frontal_idxs]}")

# --- Global plotting configuration ---
# Fixed y-limits make cross-mode comparisons easier.
Y_LIMITS = {
    'erp': (-0.4, 0.8),   # arbitrary units (simulation); label kept as uV for convention
    'psd': (-30, 5),      # dB (depends on scaling and noise model)
    'ispc': (0, 1.0)      # PLV in [0, 1]
}


def compute_ispc_value(data, sfreq, target_freq, time_window_idx, ch_idx_a, ch_idx_b):
    """
    Compute ISPC/PLV for one subject and one condition, plus per-trial phase differences.

    Parameters
    ----------
    data : ndarray, shape (n_trials, n_channels, n_times)
        Epoched data for a single condition.
    sfreq : float
        Sampling frequency (Hz).
    target_freq : float
        Center frequency for narrow-band phase extraction (Hz).
    time_window_idx : tuple (t_start_idx, t_end_idx)
        Indices defining the time window used for phase extraction.
    ch_idx_a, ch_idx_b : array-like
        Channel index sets defining the two regions whose phase relationship is assessed.

    Returns
    -------
    plv : float
        Phase-locking value across trials (0..1).
    trial_phase_diffs : ndarray, shape (n_trials,)
        Per-trial phase difference (region A vs region B) at the mid-point of the window.
    """
    n_trials, n_ch, n_time = data.shape

    # 1) Band-pass filter around target frequency (±2 Hz)
    nyq = 0.5 * sfreq
    low = (target_freq - 2.0) / nyq
    high = (target_freq + 2.0) / nyq
    sos = butter(4, [low, high], btype='band', output='sos')

    filt_data = np.zeros_like(data)
    for i in range(n_trials):
        filt_data[i] = sosfiltfilt(sos, data[i], axis=-1)

    # 2) Hilbert transform to extract instantaneous phase
    analytic_signal = hilbert(filt_data, axis=-1)
    phase_data = np.angle(analytic_signal)  # (trials, channels, times)

    # 3) Extract time window and channel groups
    t_start, t_end = time_window_idx
    phase_a = phase_data[:, ch_idx_a, t_start:t_end]
    phase_b = phase_data[:, ch_idx_b, t_start:t_end]

    # Use the middle sample of the window as a representative phase point
    mid_point = (t_end - t_start) // 2

    trial_phase_diffs = []
    for tr in range(n_trials):
        # Region-level phase vector via spatial averaging of unit phasors
        vec_a = np.mean(np.exp(1j * phase_a[tr, :, mid_point]))
        vec_b = np.mean(np.exp(1j * phase_b[tr, :, mid_point]))

        # Phase difference between regions (A relative to B)
        diff = np.angle(vec_a / vec_b)
        trial_phase_diffs.append(diff)

    trial_phase_diffs = np.asarray(trial_phase_diffs)

    # PLV: magnitude of the average phase-difference unit vectors across trials
    plv = np.abs(np.mean(np.exp(1j * trial_phase_diffs)))

    return plv, trial_phase_diffs


def set_poster_style():
    sns.set_style("white")
    plt.rcParams.update({
        'font.family': 'sans-serif',
        'font.sans-serif': ['Arial', 'Helvetica', 'DejaVu Sans'],
        'pdf.fonttype': 42,
        'axes.linewidth': 2.5,
        'xtick.major.width': 2.0,
        'ytick.major.width': 2.0,
        'xtick.major.size': 12,
        'ytick.major.size': 12
    })
def plot_simulation_with_errors(mode_name, n_subjects=30):
    """
    Run multi-subject simulation for a given generative mode, then plot summary figures:
    ERP, PSD, ISPC, and pooled phase-difference distribution.

    Parameters
    ----------
    mode_name : str
        Simulation mode (must be supported by simulate_data), e.g.:
        'erp', 'induced', 'ispc', 'slope', 'intercept'
    n_subjects : int
        Number of simulated subjects.
    """
    print(f"\n--- Processing Mode: {mode_name} (Simulating {n_subjects} Subjects) ---")

    # Containers keyed by class: each stores per-subject results
    erp_store = {0: [], 1: []}           # each entry: (n_times,)
    psd_store = {0: [], 1: []}           # each entry: (n_freqs,)
    ispc_store = {0: [], 1: []}          # each entry: scalar PLV
    phase_diffs_pool = {0: [], 1: []}    # pooled per-trial diffs across subjects

    times = None
    freqs = None

    # ISPC time window (seconds): 0.2 to 0.6 s
    # (converted to indices per subject after times is known)
    ispc_t0, ispc_t1 = 0.2, 0.6

    for sub in range(n_subjects):
        # IMPORTANT: pass script-level configuration into simulate_data so settings are consistent
        X, y, t_ = simulate_data(
            sub_id=sub,
            mode=mode_name,
            target_freq=10.0,
            noise_scale_=noise_scale,
            sfreq=SFREQ,
            tmin=TMIN,
            tmax=TMAX,
            n_trials=N_TOTAL_TRIALS,
            n_channels=N_CHANNELS,
            n_classes=N_CLASSES,
            frontal=frontal_idxs,
            posterior=posterior_idxs,
        )
        times = t_

        # Convert ISPC time window to indices
        t_idx_start = np.searchsorted(times, ispc_t0)
        t_idx_end = np.searchsorted(times, ispc_t1)

        for c in range(N_CLASSES):
            idx = (y == c)
            X_class = X[idx]  # shape: (n_trials_per_class, n_channels, n_times)

            # --- A) ERP: grand mean across trials and channels for this subject & class ---
            # Trial mean -> channel mean -> time series
            sub_erp = np.mean(np.mean(X_class, axis=0), axis=0)
            erp_store[c].append(sub_erp)

            # --- B) PSD: Welch; average over trials and channels (subject level) ---
            f_, psds = welch(X_class, fs=SFREQ, nperseg=int(SFREQ), axis=-1)  # psds: (trials, ch, freqs)
            freqs = f_
            sub_psd_raw = np.mean(np.mean(psds, axis=0), axis=0)  # (freqs,)
            sub_psd_db = 10.0 * np.log10(sub_psd_raw)
            psd_store[c].append(sub_psd_db)

            # --- C) ISPC/PLV between frontal and posterior channel groups ---
            plv, diffs = compute_ispc_value(
                X_class, SFREQ, 10.0, (t_idx_start, t_idx_end),
                ch_idx_a=np.asarray(frontal_idxs, dtype=int),
                ch_idx_b=np.asarray(posterior_idxs, dtype=int),
            )
            ispc_store[c].append(plv)
            phase_diffs_pool[c].extend(diffs.tolist())


    # ========================= Plotting (Decoding-matched Style) =========================
    set_poster_style()
    
    # Use the same canvas size as the decoding plot so you can place them side-by-side later
    fig, axes = plt.subplots(1, 3, figsize=(18, 5), constrained_layout=False)
    ax1, ax2, ax3 = axes
    
    # Match decoding palette (LDA/SVM-like colors for classes)
    colors = ['#3498db', '#ff7f0e']  # blue, orange
    # Larger typography
    LABEL_FS = 24
    TICK_FS = 20
    LEGEND_FS = 18
    # ------------------ Panel 1: ERP (Mean ± SEM across subjects) ------------------
    for c in range(N_CLASSES):
        data_arr = np.asarray(erp_store[c])  # (n_subjects, n_times)
        mu = np.mean(data_arr, axis=0)
        s = sem(data_arr, axis=0)
    
        ax1.plot(times, mu, color=colors[c], linewidth=3, label=f'Class {c}')
        ax1.fill_between(times, mu - s, mu + s, color=colors[c], alpha=0.2, lw=0)
    
    ax1.axvline(0, color='k', linestyle=':', linewidth=2, alpha=0.5)
    # ax1.set_title(f'{mode_name}: ERP', fontsize=TITLE_FS, pad=12)
    ax1.set_xlabel('Time (s)', fontsize=LABEL_FS, labelpad=10)
    ax1.set_ylabel('Amplitude (a.u.)', fontsize=LABEL_FS, labelpad=10)
    ax1.set_xlim([times[0], times[-1]])
    ax1.set_ylim(Y_LIMITS['erp'])
    ax1.tick_params(axis='both', which='major', labelsize=TICK_FS)
    ax1.legend(fontsize=LEGEND_FS, frameon=False, loc='upper right')
    ax1.spines['top'].set_visible(False)
    ax1.spines['right'].set_visible(False)
    
    # ------------------ Panel 2: PSD (Mean ± SEM across subjects) ------------------
    for c in range(N_CLASSES):
        data_arr = np.asarray(psd_store[c])  # (n_subjects, n_freqs)
        mu = np.mean(data_arr, axis=0)
        s = sem(data_arr, axis=0)
    
        ax2.plot(freqs, mu, color=colors[c], linewidth=3, label=f'Class {c}')
        ax2.fill_between(freqs, mu - s, mu + s, color=colors[c], alpha=0.2, lw=0)
    
    # ax2.set_title(f'{mode_name}: PSD', fontsize=TITLE_FS, pad=12)
    ax2.set_xlabel('Frequency (Hz)', fontsize=LABEL_FS, labelpad=10)
    ax2.set_ylabel('Power (dB)', fontsize=LABEL_FS, labelpad=10)
    ax2.set_xlim(1, 40)
    ax2.set_ylim(Y_LIMITS['psd'])
    ax2.tick_params(axis='both', which='major', labelsize=TICK_FS)
    ax2.spines['top'].set_visible(False)
    ax2.spines['right'].set_visible(False)
    
    # ------------------ Panel 3: ISPC/PLV bar (Mean ± SEM) + polar inset ------------------
    means = [np.mean(ispc_store[0]), np.mean(ispc_store[1])]
    errors = [sem(ispc_store[0]), sem(ispc_store[1])]
    
    ax3.bar([0, 1], means, yerr=errors, capsize=10, color=colors, alpha=0.9)
    # ax3.set_title(f'{mode_name}: ISPC', fontsize=TITLE_FS, pad=12)
    ax3.set_xticks([0, 1])
    ax3.set_xticklabels(['Class 0', 'Class 1'], fontsize=TICK_FS)
    ax3.set_ylabel('PLV', fontsize=LABEL_FS, labelpad=10)
    ax3.set_ylim(Y_LIMITS['ispc'])
    ax3.tick_params(axis='both', which='major', labelsize=TICK_FS)
    ax3.spines['top'].set_visible(False)
    ax3.spines['right'].set_visible(False)
    
    # Inset: phase-difference distribution (pooled across subjects)
    ax_in = ax3.inset_axes([0.50, 0.50, 0.45, 0.45], projection='polar')
    for c in range(N_CLASSES):
        bins = np.linspace(-np.pi, np.pi, 25)
        hist, bin_edges = np.histogram(phase_diffs_pool[c], bins=bins, density=True)
        width = bin_edges[1] - bin_edges[0]
        ax_in.bar(bin_edges[:-1], hist, width=width, color=colors[c], alpha=0.35, align='edge')
    
    # ax_in.set_title('Phase Δ', fontsize=12, pad=6)
    ax_in.set_yticklabels([])
    ax_in.set_xticks([0, np.pi/2, np.pi, 3*np.pi/2])
    ax_in.set_xticklabels(['0', 'π/2', 'π', '3π/2'], fontsize=14)
    ax_in.tick_params(axis='x', labelsize=14)
    ax_in.tick_params(axis='x', pad=-6)
    # ax_in.set_xticklabels([])
    
    # Clean spacing similar to your decoding figure
    plt.tight_layout()
    
    if OUTPLOT == True:
        save_path = os.path.join(RESULT_DIR, f'SimulationSummary_N{N_SUBS_TO_RUN}_{mode_name}.png')
        plt.savefig(save_path, dpi=300, bbox_inches='tight')
        print(f"Figure saved to: {save_path}")
    
    plt.show()

# ========================= Run =========================
# Runtime scales approximately linearly with N_SUBS_TO_RUN.
if __name__ == '__main__':
    # Runtime scales approximately linearly with N_SUBS_TO_RUN.
    # Runs all 5 generative modes sequentially.
    modes = ['erp', 'induced', 'ispc', 'slope', 'intercept']
    for m in modes:
        plot_simulation_with_errors(m, n_subjects=N_SUBS_TO_RUN)


